version: "3.8"
services:
  backend:
    build: .
    # This means that if we make a change to our one app, it will be mapped to our entire docker container.
    volumes:
      - .:/projects
    # The second one is the docker port from 0.0.0.0, the first port is our localhost port for 127.0.0.1 or localhost.
    ports:
      - 8000:8000
